import React from 'react';
import { StyleProp, ViewStyle, TextStyle } from 'react-native';
import { LinkMatcher, LinkType } from './linkParser';
import { LeftRightStyle, IMessage } from './Models';
export type MessageTextProps<TMessage extends IMessage> = {
    position?: 'left' | 'right';
    currentMessage: TMessage;
    containerStyle?: LeftRightStyle<ViewStyle>;
    textStyle?: LeftRightStyle<TextStyle>;
    linkStyle?: LeftRightStyle<TextStyle>;
    customTextStyle?: StyleProp<TextStyle>;
    onPress?: (message: TMessage, url: string, type: LinkType) => void;
    matchers?: LinkMatcher[];
    email?: boolean;
    phone?: boolean;
    url?: boolean;
    hashtag?: boolean;
    mention?: boolean;
    hashtagUrl?: string;
    mentionUrl?: string;
    stripPrefix?: boolean;
};
export declare const MessageText: React.FC<MessageTextProps<IMessage>>;
