export const DATE_FORMAT = 'D MMMM'
export const TIME_FORMAT = 'LT'

export const TEST_ID = {
  WRAPPER: 'GC_WRAPPER',
  LOADING_WRAPPER: 'GC_LOADING_CONTAINER',
  SEND_TOUCHABLE: 'GC_SEND_TOUCHABLE',
}
